language: python
python:
  - 3.6
  - nightly
install:
  - pip3 install -r requirements.txt
  - pip3 install python-coveralls
  - pip3 install pytest
  - pip3 install pytest-cov 
script:
  - pytest --cov=clusterhealthz clusterhealthz_tests.py
after_success:  
  - coveralls 