---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-clusterhealthz
spec:
  replicas: {{ groups['worker-nodes'] | length }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: clusterhealthz
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values:
{% for host in groups['worker-nodes'] %}
                   - {{ host }}
{% endfor %}
      containers:
      - name: deployment-clusterhealthz
        image: registryurl/clusterhealthz:0.0.1
        env:
          - service: "clusterhealthz"
            value: "service-clusterhealthz"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: cci-registry-token
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
  name: clusterhealthz
spec:
  selector:
    service: clusterhealthz
  ports:
  - name: clusterhealthz
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31011
    type: NodePort